<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ora</name>
   <tag></tag>
   <elementGuidId>63d2e234-ec3b-49d8-90a7-ea55658426cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//[@id='oraInizio_prenotazione']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
